# Generated by Django 4.2.6 on 2023-11-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Registration",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150, null=True)),
                ("Email", models.EmailField(max_length=150)),
                ("password", models.CharField(max_length=150)),
            ],
        ),
    ]
